all:
	g++ -O3 -s sServer.cpp -o sServer.exe -l ws2_32
	g++ -O3 -s sClient.cpp -o sClient.exe -l ws2_32

clean:
	del -f a.exe

s:
	g++ -O3 -s sServer.cpp -o sServer.exe -l ws2_32
	
c:
	g++ -O3 -s sClient.cpp -o sClient.exe -l ws2_32



