all:
	g++ -O3 -s sniffer.cpp -l ws2_32

clean:
	del -f a.exe

s:
	g++ -O3 -s sniffer.cpp -o sniffer.exe -l ws2_32
	
sniffer:
	g++ -O3 -s sniffer.cpp -o sniffer.exe -l ws2_32
	
32:
	g++ -O3 -s sniffer.cpp -o sniffer32.exe -l ws2_32
	
64:
	g++ -O3 -s sniffer.cpp -o sniffer64.exe -l ws2_32
